### ISSUE TITLE
Type error during rebuild

### ISSUE THREAD

**Issue by wgevaert** [WikibaseSolutions/SemanticStructuredDiscussions#11]
On a dev wiki, I received the following error during a run of SMW/RebuildData.php:
```
TypeError: SemanticStructuredDiscussions\StructuredDiscussions\SDTopic::getCreator(): Return value must be of type string, bool returned
Backtrace:
from /var/www/html/extensions/SemanticStructuredDiscussions/src/StructuredDiscussions/SDTopic.php(85)
#0 /var/www/html/extensions/SemanticStructuredDiscussions/src/SemanticMediaWiki/Annotators/TopicAnnotators/CreatorAnnotator.php(37): SemanticStructuredDiscussions\StructuredDiscussions\SDTopic->getCreator()
#1 /var/www/html/extensions/SemanticStructuredDiscussions/src/SemanticMediaWiki/DataAnnotator.php(106): SemanticStructuredDiscussions\SemanticMediaWiki\Annotators\TopicAnnotators\CreatorAnnotator->addAnnotation()
#2 /var/www/html/extensions/SemanticStructuredDiscussions/src/SemanticMediaWiki/DataAnnotator.php(58): SemanticStructuredDiscussions\SemanticMediaWiki\DataAnnotator->addTopicAnnotations()
#3 /var/www/html/extensions/SemanticStructuredDiscussions/src/Hooks.php(86): SemanticStructuredDiscussions\SemanticMediaWiki\DataAnnotator->addAnnotations()
#4 /var/www/html/includes/HookContainer/HookContainer.php(338): SemanticStructuredDiscussions\Hooks::onBeforeDataUpdateComplete()
#5 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#6 /var/www/html/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run()
#7 /var/www/html/extensions/SemanticMediaWiki/src/Store.php(233): Hooks::run()
#8 /var/www/html/extensions/SemanticMediaWiki/src/DataUpdater.php(418): SMW\Store->updateData()
#9 /var/www/html/extensions/SemanticMediaWiki/src/DataUpdater.php(297): SMW\DataUpdater->updateData()
#10 /var/www/html/extensions/SemanticMediaWiki/src/DataUpdater.php(197): SMW\DataUpdater->runUpdate()
#11 /var/www/html/extensions/SemanticMediaWiki/src/ParserData.php(469): SMW\DataUpdater->doUpdate()
#12 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(305): SMW\ParserData->updateStore()
#13 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(218): SMW\MediaWiki\Jobs\UpdateJob->updateStore()
#14 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(139): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#15 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#16 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#17 /var/www/html/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(468): SMW\SQLStore\Rebuilder\Rebuilder->rebuild()
#18 /var/www/html/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(385): SMW\Maintenance\DataRebuilder->doUpdateById()
#19 /var/www/html/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(224): SMW\Maintenance\DataRebuilder->rebuildAll()
#20 /var/www/html/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#21 /var/www/html/maintenance/includes/MaintenanceRunner.php(309): SMW\Maintenance\rebuildData->execute()
#22 /var/www/html/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#23 /var/www/html/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#24 {main}
```
So rebuildData was interrupted. Would prefer if it was a bit more forgiving/informative than this type error.

**Comment by marijnvanwezel** [comment]
Is this still a problem?

**Comment by ViktorSchelling** [comment]
Yes

**Comment by wgevaert** [comment]
Yes, here is a screenshot of a chat message of someone who has this issue:
<img width="599" alt="Screenshot 2024-05-22 at 8 56 07 AM" src="https://github.com/WikibaseSolutions/SemanticStructuredDiscussions/assets/56224691/cc0bad48-f017-4d7a-acab-aa4892b12751">

This was on a prod wiki
